[workspace]
members = ["src-tauri"]
resolver = "3"

[workspace.package]
homepage = "https://github.com/ferreira-tb/fix-me"
repository = "https://github.com/ferreira-tb/fix-me"
authors = ["Andrew Ferreira <andrew.shien2@gmail.com>"]
license = "MIT"
edition = "2024"
rust-version = "1.91"
publish = false

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
strip = "symbols"

[profile.preview]
inherits = "release"
codegen-units = 16
lto = "off"
opt-level = 0
debug = true
debug-assertions = true

[workspace.lints.rust]
async_fn_in_trait = "allow"
dangling_pointers_from_temporaries = "deny"
unfulfilled_lint_expectations = "deny"
unsafe_op_in_unsafe_fn = "deny"
variant_size_differences = "warn"

[workspace.lints.clippy]
clone_on_ref_ptr = "deny"
dbg_macro = "deny"
filetype_is_file = "deny"
get_unwrap = "deny"
large_enum_variant = "deny"
map_unwrap_or = "allow"
match_wildcard_for_single_variants = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
missing_safety_doc = "deny"
module_name_repetitions = "allow"
must_use_candidate = "allow"
needless_borrow = "deny"
needless_for_each = "allow"
rc_buffer = "deny"
rc_mutex = "deny"
rest_pat_in_fully_bound_structs = "deny"
similar_names = "allow"
struct_field_names = "allow"
unnecessary_safety_comment = "deny"
unsafe_derive_deserialize = "allow"
useless_conversion = "deny"

[workspace.lints.clippy.pedantic]
level = "deny"
priority = -1
